In [53]:
from sklearn import tree
import pandas as pd
import os

In [59]:
data = pd.read_csv('../../Resources/bio_vars_2050.csv')

In [60]:
data.drop(['ac45bi501', 'ac45bi5010', 'ac45bi5011', 'ac45bi5012', 'ac45bi5013',
       'ac45bi5014', 'ac45bi5015', 'ac45bi5016', 'ac45bi5017', 'ac45bi5018',
       'ac45bi5019', 'ac45bi502', 'ac45bi503', 'ac45bi504', 'ac45bi505',
       'ac45bi506', 'ac45bi507', 'ac45bi508', 'ac45bi509'], axis = 1, inplace = True)
data.dropna(axis = 0, how = 'any', inplace = True)
data.rename(columns={'bc45bi501': 'Annual Mean Temperature', 
                     'bc45bi5010': 'Mean Diurnal Range (Mean of monthly (max temp - min temp))',
                     'bc45bi5011': 'Isothermality',
                     'bc45bi5012': 'Temperature Seasonality',
                     'bc45bi5013': 'Max Temperature of Warmest Month',
                     'bc45bi5014': 'Min Temperature of Coldest Month',
                     'bc45bi5015': 'Temperature Annual Range',
                     'bc45bi5016': 'Mean Temperature of Wettest Quarter',
                     'bc45bi5017': 'Mean Temperature of Driest Quarter',
                     'bc45bi5018': 'Mean Temperature of Warmest Quarter',
                     'bc45bi5019': 'Mean Temperature of Coldest Quarter',
                     'bc45bi502': 'Annual Precipitation',
                     'bc45bi503': 'Precipitation of Wettest Month',
                     'bc45bi504': 'Precipitation of Driest Month',
                     'bc45bi505': 'Precipitation Seasonality (Coefficient of Variation)',
                     'bc45bi506': 'Precipitation of Wettest Quarter',
                     'bc45bi507': 'Precipitation of Driest Quarter',
                     'bc45bi508': 'Precipitation of Warmest Quarter',
                     'bc45bi509': 'Precipitation of Coldest Quarter',
                    }, inplace=True)

data = data[['raster_frame', 'Precipitation of Driest Month', 'Temperature Seasonality', 'Precipitation of Driest Quarter',
             'Annual Precipitation', 'Precipitation of Warmest Quarter']]


# data.columns
data.head()

,raster_frame,Precipitation of Driest Month,Temperature Seasonality,Precipitation of Driest Quarter,Annual Precipitation,Precipitation of Warmest Quarter
0,0,5418.0,2300.0,266.0,106.0,62.0
1,0,5387.0,2314.0,266.0,106.0,61.0
2,0,5422.0,2279.0,267.0,107.0,62.0
3,0,5445.0,2259.0,267.0,106.0,62.0
4,0,5454.0,2306.0,266.0,107.0,58.0

In [61]:
target = data['raster_frame']
target_names = ["negative", "positive"]

In [62]:
new_data = data.drop("raster_frame", axis=1)
feature_names = new_data.columns
new_data.head()

,Precipitation of Driest Month,Temperature Seasonality,Precipitation of Driest Quarter,Annual Precipitation,Precipitation of Warmest Quarter
0,5418.0,2300.0,266.0,106.0,62.0
1,5387.0,2314.0,266.0,106.0,61.0
2,5422.0,2279.0,267.0,107.0,62.0
3,5445.0,2259.0,267.0,106.0,62.0
4,5454.0,2306.0,266.0,107.0,58.0

In [63]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.9585578826914585

In [64]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)
rf = rf.fit(new_data, target)
prediction = rf.predict_proba(new_data)
print(prediction)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]

In [65]:
rf.score(new_data, target)

0.9984805823168271

In [35]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.173561859045159, 'Unnamed: 0'),
 (0.08974963105149125, 'Precipitation of Driest Month'),
 (0.05682142126086838, 'Temperature Seasonality'),
 (0.0543914116644044, 'Precipitation of Driest Quarter'),
 (0.05119224055731246, 'Mean Temperature of Coldest Quarter'),
 (0.050703036226675796, 'Annual Precipitation'),
 (0.05019256893712247, 'Precipitation of Warmest Quarter'),
 (0.048451870167346825, 'Mean Temperature of Wettest Quarter'),
 (0.0453441539348269, 'Precipitation of Wettest Quarter'),
 (0.04381879014798447, 'Isothermality'),
 (0.043417894201306186, 'Mean Temperature of Warmest Quarter'),
 (0.042153990622897174, 'Precipitation of Coldest Quarter'),
 (0.03841539589262608, 'Temperature Annual Range'),
 (0.03767718769824706, 'Max Temperature of Warmest Month'),
 (0.03404942089055195, 'Precipitation Seasonality (Coefficient of Variation)'),
 (0.03222694045620664, 'Mean Temperature of Driest Quarter'),
 (0.030131434321629326, 'Annual Mean Temperature'),
 (0.029299963006261615,
  'Mean Diurnal Range (Mean of monthly (max temp - min temp))'),
 (0.028051418384774537, 'Min Temperature of Coldest Month'),
 (0.0203493715323075, 'Precipitation of Wettest Month')]

In [39]:
data['Prediction'] = prediction[:,1]
# len(prediction)
# data.count
data.tail()

,Unnamed: 0,Annual Mean Temperature,Mean Diurnal Range (Mean of monthly (max temp - min temp)),Isothermality,Temperature Seasonality,Max Temperature of Warmest Month,Min Temperature of Coldest Month,Temperature Annual Range,Mean Temperature of Wettest Quarter,Mean Temperature of Driest Quarter,...,Annual Precipitation,Precipitation of Wettest Month,Precipitation of Driest Month,Precipitation Seasonality (Coefficient of Variation),Precipitation of Wettest Quarter,Precipitation of Driest Quarter,Precipitation of Warmest Quarter,Precipitation of Coldest Quarter,raster_frame,Prediction
1688827,1688828,109.0,218.0,8.0,338.0,61.0,8.0,46.0,137.0,36.0,...,158.0,40.0,8268.0,321.0,-68.0,389.0,213.0,138.0,0,0.000
1688828,1688829,113.0,224.0,11.0,320.0,57.0,8.0,46.0,130.0,35.0,...,160.0,40.0,8363.0,327.0,-67.0,394.0,218.0,143.0,0,0.000
1688829,1688830,120.0,232.0,15.0,290.0,53.0,7.0,46.0,119.0,33.0,...,164.0,40.0,8502.0,338.0,-64.0,402.0,227.0,151.0,0,0.005
1688830,1688831,123.0,236.0,17.0,277.0,51.0,7.0,47.0,114.0,31.0,...,166.0,40.0,8563.0,343.0,-63.0,406.0,230.0,154.0,0,0.000
1688831,1688832,124.0,237.0,18.0,273.0,50.0,7.0,48.0,112.0,31.0,...,166.0,40.0,8578.0,344.0,-63.0,407.0,231.0,156.0,0,0.000